class CfgAmmo {
	class TBD_MORTARS_105mm_SHELL_AMMO_HE;

	class TBD_MORTARS_105mm_SHELL_AMMO_LASER: TBD_MORTARS_105mm_SHELL_AMMO_HE {
		model = QPATHTOF(TBD_MORTARS_105mm_SHELL_LASER\TBD_MORTARS_105mm_SHELL_LASER);
	};
};
