class CfgMagazines {
	class TBD_MORTARS_105mm_ROUND_HE_CHARGE_MAG_1;

	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1: TBD_MORTARS_105mm_ROUND_HE_CHARGE_MAG_1 {
		scope = 1;
		scopeArsenal = 1;
		author = "TBD Team";
		displayName = CSTRING(LASER_CHARGE_1);
		displayNameShort = CSTRING(LASER_CHARGE_1);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_1);
		descriptionShort = CSTRING(LASER_CHARGE_DESC);
		initSpeed = 74;
		mass = 70;
		count = 1;
		ammo = QUOTE(TBD_MORTARS_105mm_SHELL_AMMO_LASER);
		type = 256;
	};
	
	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_2: TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1 {
		displayName = CSTRING(LASER_CHARGE_2);
		displayNameShort = CSTRING(LASER_CHARGE_2);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_2);
		initSpeed = 117;
	};

	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_3: TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1 {
		displayName = CSTRING(LASER_CHARGE_3);
		displayNameShort = CSTRING(LASER_CHARGE_3);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_3);
		initSpeed = 160;
	};

	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_4: TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1 {
		displayName = CSTRING(LASER_CHARGE_4);
		displayNameShort = CSTRING(LASER_CHARGE_4);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_4);
		initSpeed = 203;
	};

	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_5: TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1 {
		displayName = CSTRING(LASER_CHARGE_5);
		displayNameShort = CSTRING(LASER_CHARGE_5);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_5);
		initSpeed = 246;
	};

	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_6: TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1 {
		displayName = CSTRING(LASER_CHARGE_6);
		displayNameShort = CSTRING(LASER_CHARGE_6);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_6);
		initSpeed = 289;
	};

	class TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_7: TBD_MORTARS_105mm_ROUND_LASER_CHARGE_MAG_1 {
		displayName = CSTRING(LASER_CHARGE_7);
		displayNameShort = CSTRING(LASER_CHARGE_7);
		model = QPATHTOF(TBD_MORTARS_105mm_ROUND_LASER\TBD_MORTARS_105mm_ROUND_LASER_CHARGE_7);
		initSpeed = 340;
	};
};
