name = "TBD Mortars"
author = "TBD Team"
prefix = "tbd_mortars"
mainprefix = "x"

[files]
include=["mod.cpp"]
exclude=[".vscode/**/*"]

[version]
major=0
minor=6
patch=4

git_hash=0

[hemtt.release]
sign   =true
archive=false

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "2369477168", # Advanced Developer Tools
    #"541888371", # CUP Vehicles
    #"497661914", # CUP Units
    #"497660133", # CUP Weapons
    "3356373534", # D-20
]

mission = "mortartest.Stratis"

parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
]
